### ISSUE TITLE
Feat: 홈 등급 게이지 구현

### ISSUE THREAD

**Issue by 3o14** [3o14/footprint#2]
## 🚧 Description
홈 배너에 있는 게이지를 구현한다.
게이지는 모든 방명록의 총 발자국 개수와 방문 횟수에 따라 결정된다.

## ✅ Todo
- [ ] 등급 체계 정하기
- [ ] 발자국 한 개당 점수 설정하기
- [ ] 방문 횟수 배점 설정하기
- [ ] 점수에 따른 등급 표시하기
- [ ] 퍼센테이지 게이지바로 표시하기
